version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
volumes:
  db:
    driver: local
