-- AlterTable
ALTER TABLE "prestadores" ALTER COLUMN "estado" SET DEFAULT E'INATIVO',
ALTER COLUMN "classificacao" SET DEFAULT 0,
ALTER COLUMN "numAvaliacoes" SET DEFAULT 0,
ALTER COLUMN "rate" SET DEFAULT 0;
